# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'page1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(2000, 2000)
        Form.setStyleSheet("background-color:rgb(222, 250, 255)")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setMaximumSize(QtCore.QSize(1500, 900))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem = QtWidgets.QSpacerItem(20, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_4.addItem(spacerItem, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setMaximumSize(QtCore.QSize(1000,1000))
        font = QtGui.QFont()
        font.setFamily("Neo Sans W23 Bold")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(98, 98, 98);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 1, 1, 1)
        self.tableWidget_P1 = QtWidgets.QTableWidget(self.frame)
        font = QtGui.QFont()
        font.setFamily("Neo Sans W23")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget_P1.setFont(font)
        self.tableWidget_P1.setStyleSheet("QTableWidget {\n"
"    background-color:rgb(248, 248, 248); /* Background color of the table */\n"
"    selection-background-color: rgb(153, 153, 153); /* Background color when a cell is selected */\n"
"    gridline-color: rgb(153, 153, 153); /* Color of gridlines */\n"
"\n"
"    /* Optional: Set other properties */\n"
"    color: rgb(98, 98, 98); /* Text color */\n"
"    font-size: 12pt; /* Font size */\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    padding: 5px; /* Padding for cell content */\n"
"    border-bottom: 2px solid #d0d0d0; /* Border between rows */\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: #a6a6a6; /* Background color of selected cell */\n"
"    color: #ffffff; /* Text color of selected cell */\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color:rgb(98, 98, 98); /* Background color of header sections */\n"
"    color: #ffffff; /* Text color of header sections */\n"
"    padding: 6px; /* Padding for header sections */\n"
"    border: 2px solid #ffffff; /* Border around header sections */\n"
"    font-size: 12pt; /* Set your desired font size */\n"
"font-family: Neo Sans W23 Bold;\n"
"}\n"
"\n"
"QTableWidget::horizontalHeader {\n"
"    border: 1px solid rgb(0, 0, 0); /* Border at the bottom of the header */\n"
"}\n"
"\n"
"QTableWidget::verticalHeader {\n"
"    border: 1px solid rgb(0, 0, 0); /* Border on the right of the header */\n"
"}\n"
"\n"
"QTableWidget::horizontalHeader::section,\n"
"QTableWidget::verticalHeader::section {\n"
"    border: 1px solid #ffffff; /* Border around header sections */\n"
"}")
        self.tableWidget_P1.setRowCount(1)
        self.tableWidget_P1.setColumnCount(2)
        self.tableWidget_P1.setObjectName("tableWidget_P1")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_P1.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_P1.setHorizontalHeaderItem(1, item)
        self.tableWidget_P1.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_P1.setColumnWidth(0,650)
        self.tableWidget_P1.setColumnWidth(1,300)
        # self.tableWidget_P1.horizontalHeader().setDefaultSectionSize(0)
        self.tableWidget_P1.setMaximumWidth(1000)
        # self.tableWidget_P1.horizontalHeader().setMinimumSectionSize(52)
        self.tableWidget_P1.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_P1.verticalHeader().setSortIndicatorShown(True)
        # self.tableWidget_P1.verticalHeader().setStretchLastSection(True)
        self.gridLayout_4.addWidget(self.tableWidget_P1, 2, 1, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setMaximumSize(QtCore.QSize(300, 16777215))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("Neo Sans W23")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("border: 2px solid;\n"
"border-radius: 10px;\n"
"background-color:rgb(98, 98, 98);\n"
"color: rgb(222, 250, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.pushButton_P1_Edit_2 = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_P1_Edit_2.sizePolicy().hasHeightForWidth())
        self.pushButton_P1_Edit_2.setSizePolicy(sizePolicy)
        self.pushButton_P1_Edit_2.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("Neo Sans W23")
        font.setPointSize(-1)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.pushButton_P1_Edit_2.setFont(font)
        self.pushButton_P1_Edit_2.setStyleSheet("QPushButton {\n"
"    background-color:rgb(153, 153, 153);\n"
"    color:rgb(222, 250, 255);\n"
"    border: 1px solid;\n"
"    padding: 10px 20px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    display: inline-block;\n"
"    font-size: 28px;\n"
"    margin: 4px 2px;\n"
"    cursor: pointer;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(153, 153, 153);\n"
"    color:rgb(255, 255, 255);\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed  {\n"
"    background-color:rgb(255, 255, 255);\n"
"    color:rgb(0, 0, 0);}")
        self.pushButton_P1_Edit_2.setObjectName("pushButton_P1_Edit_2")
        self.verticalLayout.addWidget(self.pushButton_P1_Edit_2)
        self.pushButton_P1_Edit = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_P1_Edit.sizePolicy().hasHeightForWidth())
        self.pushButton_P1_Edit.setSizePolicy(sizePolicy)
        self.pushButton_P1_Edit.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("Neo Sans W23")
        font.setPointSize(-1)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.pushButton_P1_Edit.setFont(font)
        self.pushButton_P1_Edit.setStyleSheet("QPushButton {\n"
"    background-color:rgb(153, 153, 153);\n"
"    color:rgb(222, 250, 255);\n"
"    border: 1px solid;\n"
"    padding: 10px 20px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    display: inline-block;\n"
"    font-size: 28px;\n"
"    margin: 4px 2px;\n"
"    cursor: pointer;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(153, 153, 153);\n"
"    color:rgb(255, 255, 255);\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed  {\n"
"    background-color:rgb(255, 255, 255);\n"
"    color:rgb(0, 0, 0);}")
        self.pushButton_P1_Edit.setObjectName("pushButton_P1_Edit")
        self.verticalLayout.addWidget(self.pushButton_P1_Edit)
        self.pushButton_P1_Info = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_P1_Info.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("Neo Sans W23")
        font.setPointSize(-1)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.pushButton_P1_Info.setFont(font)
        self.pushButton_P1_Info.setStyleSheet("QPushButton {\n"
"    background-color:rgb(153, 153, 153);\n"
"    color:rgb(222, 250, 255);\n"
"    border: 1px solid;\n"
"    padding: 10px 20px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    display: inline-block;\n"
"    font-size: 28px;\n"
"    margin: 4px 2px;\n"
"    cursor: pointer;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(153, 153, 153);\n"
"    color:rgb(255, 255, 255);\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed  {\n"
"    background-color:rgb(255, 255, 255);\n"
"    color:rgb(0, 0, 0);}")
        self.pushButton_P1_Info.setObjectName("pushButton_P1_Info")
        self.verticalLayout.addWidget(self.pushButton_P1_Info)
        self.pushButton_P1_Del = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_P1_Del.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("Neo Sans W23")
        font.setPointSize(-1)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.pushButton_P1_Del.setFont(font)
        self.pushButton_P1_Del.setStyleSheet("QPushButton {\n"
"    background-color:rgb(153, 153, 153);\n"
"    color:rgb(222, 250, 255);\n"
"    border: 1px solid;\n"
"    padding: 10px 20px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    display: inline-block;\n"
"    font-size: 28px;\n"
"    margin: 4px 2px;\n"
"    cursor: pointer;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(153, 153, 153);\n"
"    color:rgb(255, 255, 255);\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed  {\n"
"    background-color:rgb(255, 255, 255);\n"
"    color:rgb(0, 0, 0);}")
        self.pushButton_P1_Del.setObjectName("pushButton_P1_Del")
        self.verticalLayout.addWidget(self.pushButton_P1_Del)
        self.gridLayout_4.addWidget(self.frame_3, 2, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Student Registeration System"))
        item = self.tableWidget_P1.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Name"))
        item = self.tableWidget_P1.horizontalHeaderItem(1)
        item.setText(_translate("Form", "ID"))
        self.label_2.setText(_translate("Form", "Options"))
        self.pushButton_P1_Edit_2.setText(_translate("Form", "Add Student"))
        self.pushButton_P1_Edit.setText(_translate("Form", "Edit Student"))
        self.pushButton_P1_Info.setText(_translate("Form", "Student Details"))
        self.pushButton_P1_Del.setText(_translate("Form", "Remove Student"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())