# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Page444.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(2000, 2000)
        # Form.setMaximumSize(QtCore.QSize(2000, 2000))
        Form.setStyleSheet("background-color:rgb(222, 250, 255)")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 1, 4, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setMaximumSize(QtCore.QSize(16777215, 70))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.lineEdit_P7_NewCName = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_P7_NewCName.setMaximumSize(QtCore.QSize(16777215, 70))
        font = QtGui.QFont()
        font.setFamily("Neo Sans W23")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_P7_NewCName.setFont(font)
        self.lineEdit_P7_NewCName.setStyleSheet("border-radius: 8px;\n"
"border: 0.5px solid black;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(98, 98, 98);\n"
"font-size: 32px;")
        self.lineEdit_P7_NewCName.setObjectName("lineEdit_P7_NewCName")
        self.verticalLayout_2.addWidget(self.lineEdit_P7_NewCName)
        self.verticalLayout_6.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 70))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.lineEdit_P7_NewCTitle = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_P7_NewCTitle.setMaximumSize(QtCore.QSize(16777215, 70))
        self.lineEdit_P7_NewCTitle.setStyleSheet("border-radius: 8px;\n"
"border: 0.5px solid black;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(98, 98, 98);\n"
"font-size: 32px;")
        self.lineEdit_P7_NewCTitle.setObjectName("lineEdit_P7_NewCTitle")
        self.verticalLayout.addWidget(self.lineEdit_P7_NewCTitle)
        self.verticalLayout_6.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.lineEdit_P7_NewCCredit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_P7_NewCCredit.setMaximumSize(QtCore.QSize(16777215, 70))
        self.lineEdit_P7_NewCCredit.setStyleSheet("border-radius: 8px;\n"
"border: 0.5px solid black;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(98, 98, 98);\n"
"font-size: 32px;")
        self.lineEdit_P7_NewCCredit.setObjectName("lineEdit_P7_NewCCredit")
        self.verticalLayout_3.addWidget(self.lineEdit_P7_NewCCredit)
        self.verticalLayout_6.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.lineEdit_P7_NewCRef = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_P7_NewCRef.setMaximumSize(QtCore.QSize(16777215, 70))
        self.lineEdit_P7_NewCRef.setStyleSheet("border-radius: 8px;\n"
"border: 0.5px solid black;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(98, 98, 98);\n"
"font-size: 32px;")
        self.lineEdit_P7_NewCRef.setObjectName("lineEdit_P7_NewCRef")
        self.verticalLayout_4.addWidget(self.lineEdit_P7_NewCRef)
        self.verticalLayout_6.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.lineEdit_P7_NewCMarks = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_P7_NewCMarks.setMaximumSize(QtCore.QSize(16777215, 70))
        self.lineEdit_P7_NewCMarks.setStyleSheet("border-radius: 8px;\n"
"border: 0.5px solid black;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(98, 98, 98);\n"
"font-size: 32px;")
        self.lineEdit_P7_NewCMarks.setObjectName("lineEdit_P7_NewCMarks")
        self.verticalLayout_5.addWidget(self.lineEdit_P7_NewCMarks)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.gridLayout_3.addLayout(self.verticalLayout_6, 1, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 1, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_P7_Cancel = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_P7_Cancel.setStyleSheet("QPushButton {\n"
"    background-color:rgb(153, 153, 153);\n"
"    color:rgb(222, 250, 255);\n"
"    border: 1px solid;\n"
"    padding: 10px 20px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    display: inline-block;\n"
"    font-size: 28px;\n"
"    margin: 4px 2px;\n"
"    cursor: pointer;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(153, 153, 153);\n"
"    color:rgb(255, 255, 255);\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed  {\n"
"    background-color:rgb(255, 255, 255);\n"
"    color:rgb(0, 0, 0);}")
        self.pushButton_P7_Cancel.setObjectName("pushButton_P7_Cancel")
        self.gridLayout_2.addWidget(self.pushButton_P7_Cancel, 0, 1, 1, 1)
        self.pushButton_P7_Confirm = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_P7_Confirm.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_P7_Confirm.setStyleSheet("QPushButton {\n"
"    background-color:rgb(153, 153, 153);\n"
"    color:rgb(222, 250, 255);\n"
"    border: 1px solid;\n"
"    padding: 10px 20px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    display: inline-block;\n"
"    font-size: 28px;\n"
"    margin: 4px 2px;\n"
"    cursor: pointer;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(153, 153, 153);\n"
"    color:rgb(255, 255, 255);\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed  {\n"
"    background-color:rgb(255, 255, 255);\n"
"    color:rgb(0, 0, 0);}")
        self.pushButton_P7_Confirm.setObjectName("pushButton_P7_Confirm")
        self.gridLayout_2.addWidget(self.pushButton_P7_Confirm, 0, 2, 1, 1)
        self.gridLayout_3.addWidget(self.frame_2, 3, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem2, 2, 3, 1, 1)
        self.gridLayout.addWidget(self.frame, 2, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 3, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 0, 2, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Course Name"))
        self.label_2.setText(_translate("Form", "Course Title"))
        self.label_3.setText(_translate("Form", "Credit Hours"))
        self.label_4.setText(_translate("Form", "Refrence Number"))
        self.label_5.setText(_translate("Form", "Marks"))
        self.pushButton_P7_Cancel.setText(_translate("Form", "Cancel"))
        self.pushButton_P7_Confirm.setText(_translate("Form", "Confirm"))
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())