# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'page10.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1046, 847)
        Form.setStyleSheet("background-color:rgb(222, 250, 255)")
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setFamily("Neo Sans W23 Bold")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(98, 98, 98);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.comboBox_P10 = QtWidgets.QComboBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(130)
        sizePolicy.setHeightForWidth(self.comboBox_P10.sizePolicy().hasHeightForWidth())
        self.comboBox_P10.setSizePolicy(sizePolicy)
        self.comboBox_P10.setMinimumSize(QtCore.QSize(40, 70))
        self.comboBox_P10.setStyleSheet("border: 2px solid;\n"
"border-radius: 10px;\n"
"background-color:rgb(98, 98, 98);\n"
"color: rgb(222, 250, 255);")
        self.comboBox_P10.setObjectName("comboBox_P10")
        self.verticalLayout.addWidget(self.comboBox_P10)
        self.pushButton_P10_Print = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.pushButton_P10_Print.setFont(font)
        self.pushButton_P10_Print.setStyleSheet("QPushButton {\n"
"    background-color:rgb(153, 153, 153);\n"
"    color:rgb(222, 250, 255);\n"
"    border: 1px solid;\n"
"    padding: 10px 20px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    display: inline-block;\n"
"\n"
"    margin: 4px 2px;\n"
"    cursor: pointer;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(153, 153, 153);\n"
"    color:rgb(255, 255, 255);\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed  {\n"
"    background-color:rgb(255, 255, 255);\n"
"    color:rgb(0, 0, 0);}")
        self.pushButton_P10_Print.setObjectName("pushButton_P10_Print")
        self.verticalLayout.addWidget(self.pushButton_P10_Print)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.pushButton_P10_back = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.pushButton_P10_back.setFont(font)
        self.pushButton_P10_back.setStyleSheet("QPushButton {\n"
"    background-color:rgb(153, 153, 153);\n"
"    color:rgb(222, 250, 255);\n"
"    border: 1px solid;\n"
"    padding: 10px 20px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    display: inline-block;\n"
"\n"
"    margin: 4px 2px;\n"
"    cursor: pointer;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(153, 153, 153);\n"
"    color:rgb(255, 255, 255);\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed  {\n"
"    background-color:rgb(255, 255, 255);\n"
"    color:rgb(0, 0, 0);}")
        self.pushButton_P10_back.setObjectName("pushButton_P10_back")
        self.verticalLayout.addWidget(self.pushButton_P10_back)
        spacerItem4 = QtWidgets.QSpacerItem(20, 300, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem4)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Neo Sans W23")
        font.setPointSize(10)
        font.setItalic(False)
        font.setKerning(True)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"padding: 50px;\n"
"color: rgb(98, 98, 98);\n"
"line-height: 200%;")
        self.plainTextEdit.setTabChangesFocus(False)
        self.plainTextEdit.setUndoRedoEnabled(False)
        self.plainTextEdit.setLineWrapMode(QtWidgets.QPlainTextEdit.WidgetWidth)
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setPlainText("")
        self.plainTextEdit.setOverwriteMode(True)
        self.plainTextEdit.setTabStopWidth(80)
        self.plainTextEdit.setTabStopDistance(80.0)
        self.plainTextEdit.setCursorWidth(0)
        self.plainTextEdit.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.plainTextEdit.setMaximumBlockCount(0)
        self.plainTextEdit.setBackgroundVisible(False)
        self.plainTextEdit.setCenterOnScroll(False)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.horizontalLayout.addWidget(self.plainTextEdit)
        spacerItem5 = QtWidgets.QSpacerItem(300, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem6, 3, 1, 1, 1)
        self.gridLayout_2.addWidget(self.frame, 0, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Student information"))
        self.pushButton_P10_Print.setText(_translate("Form", "Print"))
        self.pushButton_P10_back.setText(_translate("Form", "Back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
